module.exports = [
  {
    username: "johndoe",
    useremail: "johndoe@example.com",
    age: 28,
    location: "New York",
    mobile: "555-0191",
  },
  {
    username: "janesmith",
    useremail: "janesmith@example.com",
    age: 34,
    location: "Los Angeles",
    mobile: "555-0234",
  },
  {
    username: "michaelb",
    useremail: "michaelb@example.com",
    age: 45,
    location: "Chicago",
    mobile: "555-0345",
  },
  {
    username: "sarahk",
    useremail: "sarahk@example.com",
    age: 29,
    location: "Houston",
    mobile: "555-0487",
  },
  {
    username: "davidl",
    useremail: "davidl@example.com",
    age: 31,
    location: "Phoenix",
    mobile: "555-0598",
  },
  {
    username: "emilyr",
    useremail: "emilyr@example.com",
    age: 22,
    location: "Philadelphia",
    mobile: "555-0622",
  },
  {
    username: "robertt",
    useremail: "robertt@example.com",
    age: 38,
    location: "San Antonio",
    mobile: "555-0765",
  },
  {
    username: "lauraw",
    useremail: "lauraw@example.com",
    age: 26,
    location: "San Diego",
    mobile: "555-0899",
  },
  {
    username: "jamesm",
    useremail: "jamesm@example.com",
    age: 40,
    location: "Dallas",
    mobile: "555-0931",
  },
  {
    username: "karenh",
    useremail: "karenh@example.com",
    age: 35,
    location: "San Jose",
    mobile: "555-1044",
  },
  {
    username: "stevenp",
    useremail: "stevenp@example.com",
    age: 33,
    location: "Austin",
    mobile: "555-1122",
  },
  {
    username: "lisab",
    useremail: "lisab@example.com",
    age: 27,
    location: "Jacksonville",
    mobile: "555-1201",
  },
  {
    username: "chrisj",
    useremail: "chrisj@example.com",
    age: 36,
    location: "Fort Worth",
    mobile: "555-1345",
  },
  {
    username: "angelat",
    useremail: "angelat@example.com",
    age: 24,
    location: "Columbus",
    mobile: "555-1478",
  },
  {
    username: "kevinh",
    useremail: "kevinh@example.com",
    age: 41,
    location: "Charlotte",
    mobile: "555-1592",
  },
  {
    username: "melissam",
    useremail: "melissam@example.com",
    age: 30,
    location: "San Francisco",
    mobile: "555-1623",
  },
  {
    username: "danielg",
    useremail: "danielg@example.com",
    age: 32,
    location: "Indianapolis",
    mobile: "555-1749",
  },
  {
    username: "natalier",
    useremail: "natalier@example.com",
    age: 25,
    location: "Seattle",
    mobile: "555-1856",
  },
  {
    username: "joshuaw",
    useremail: "joshuaw@example.com",
    age: 39,
    location: "Denver",
    mobile: "555-1987",
  },
  {
    username: "amandak",
    useremail: "amandak@example.com",
    age: 28,
    location: "Washington",
    mobile: "555-2002",
  },
  {
    username: "brianm",
    useremail: "brianm@example.com",
    age: 43,
    location: "Boston",
    mobile: "555-2134",
  },
  {
    username: "heathern",
    useremail: "heathern@example.com",
    age: 37,
    location: "El Paso",
    mobile: "555-2245",
  },
  {
    username: "patrickd",
    useremail: "patrickd@example.com",
    age: 29,
    location: "Detroit",
    mobile: "555-2356",
  },
  {
    username: "rachelc",
    useremail: "rachelc@example.com",
    age: 31,
    location: "Nashville",
    mobile: "555-2467",
  },
  {
    username: "justint",
    useremail: "justint@example.com",
    age: 26,
    location: "Memphis",
    mobile: "555-2578",
  },
  {
    username: "victorias",
    useremail: "victorias@example.com",
    age: 34,
    location: "Oklahoma City",
    mobile: "555-2699",
  },
  {
    username: "ryanl",
    useremail: "ryanl@example.com",
    age: 42,
    location: "Las Vegas",
    mobile: "555-2711",
  },
  {
    username: "aliciam",
    useremail: "aliciam@example.com",
    age: 23,
    location: "Louisville",
    mobile: "555-2833",
  },
  {
    username: "matthewp",
    useremail: "matthewp@example.com",
    age: 38,
    location: "Baltimore",
    mobile: "555-2944",
  },
  {
    username: "hannahf",
    useremail: "hannahf@example.com",
    age: 27,
    location: "Milwaukee",
    mobile: "555-3055",
  },
  {
    username: "danielg",
    useremail: "danielg@example.com",
    age: 32,
    location: "Indianapolis",
    mobile: "555-1749",
  },
  {
    username: "heathern",
    useremail: "heathern@example.com",
    age: 37,
    location: "El Paso",
    mobile: "555-2245",
  },
  {
    username: "matthewp",
    useremail: "matthewp@example.com",
    age: 38,
    location: "Baltimore",
    mobile: "555-2944",
  },
  {
    username: "angelat",
    useremail: "angelat@example.com",
    age: 24,
    location: "Columbus",
    mobile: "555-1478",
  },
  {
    username: "emilyr",
    useremail: "emilyr@example.com",
    age: 22,
    location: "Philadelphia",
    mobile: "555-0622",
  },
  {
    username: "ryanl",
    useremail: "ryanl@example.com",
    age: 42,
    location: "Las Vegas",
    mobile: "555-2711",
  },
  {
    username: "amandak",
    useremail: "amandak@example.com",
    age: 28,
    location: "Washington",
    mobile: "555-2002",
  },
  {
    username: "hannahf",
    useremail: "hannahf@example.com",
    age: 27,
    location: "Milwaukee",
    mobile: "555-3055",
  },
  {
    username: "robertt",
    useremail: "robertt@example.com",
    age: 38,
    location: "San Antonio",
    mobile: "555-0765",
  },
  {
    username: "victorias",
    useremail: "victorias@example.com",
    age: 34,
    location: "Oklahoma City",
    mobile: "555-2699",
  },
];
