version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: sql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "8000:3306"
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network

  server:
    build:
      context: ./dockerizedCache
      dockerfile: redis.dockerFile # Correct path
    container_name: server-container
    environment:
      DB_HOST: sql-container
      DB_PORT: 3306
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: testdb
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
    ports:
      - "7000:7000"
    depends_on:
      - mysql
      - redis
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
